[id]
  languageName = "Bahasa Indonesia"
  contentDir = "content/id"
  weight = 5
  [id.params]
    languageISO = "ID"
    languageTag = "id-ID"
    footer = '©webzahra'
    # alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks versi 1.0 telah tiba!</a>'

[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = '©webzahra'
    # alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'
